### ISSUE TITLE
产品组提交Issue指南

### ISSUE THREAD

**Issue by RobertIndie** [wuhan2020/data-sync#30]
1. 在issues面板中点击New issue。
2. 填写issue的Title，Title格式为："[需求类型]需求标题"，如：“[Feature] 添加一个新特性”。请按所规定的需求类型进行填写，可选的需求类型有：Feature、Enhancement、Bug。（如需要添加新的需求类型，请联系项目管理员）
当发布issue后，机器人将会自动添加label。

3. 填写issue的内容，描述需求的详细内容，支持markdown格式。
4. 点击submit new issue按钮即可发布issue。需要认领issue的同学请回复/self-assign。

Issue示例如图
![image](https://user-images.githubusercontent.com/16974619/73449580-741a5d00-439e-11ea-8fd6-cab19e489e60.png)

**Comment by frank-zsy** [comment]
棒，我会把这个 Issue Pin 住，让产品小伙伴们可以明显看到

**Comment by boykait** [comment]
> 1. 在issues面板中点击New issue。
> 2. 填写issue的Title，Title格式为："[需求类型]需求标题"，如：“[Feature] 添加一个新特性”。请按所规定的需求类型进行填写，可选的需求类型有：Feature、Enhancement、Bug。（如需要添加新的需求类型，请联系项目管理员）
>    当发布issue后，机器人将会自动添加label。
> 3. 填写issue的内容，描述需求的详细内容，支持markdown格式。
> 4. 点击submit new issue按钮即可发布issue。需要认领issue的同学请回复/self-assign。
> 
> Issue示例如图
> ![image](https://user-images.githubusercontent.com/16974619/73449580-741a5d00-439e-11ea-8fd6-cab19e489e60.png)

你这流程图看不到啊

**Comment by RobertIndie** [comment]
> > 1. 在issues面板中点击New issue。
> > 2. 填写issue的Title，Title格式为："[需求类型]需求标题"，如：“[Feature] 添加一个新特性”。请按所规定的需求类型进行填写，可选的需求类型有：Feature、Enhancement、Bug。（如需要添加新的需求类型，请联系项目管理员）
> >    当发布issue后，机器人将会自动添加label。
> > 3. 填写issue的内容，描述需求的详细内容，支持markdown格式。
> > 4. 点击submit new issue按钮即可发布issue。需要认领issue的同学请回复/self-assign。
> > 
> > Issue示例如图
> > ![image](https://user-images.githubusercontent.com/16974619/73449580-741a5d00-439e-11ea-8fd6-cab19e489e60.png)
> 
> 你这流程图看不到啊

我这里只post了issue的示例图，图片地址为：https://user-images.githubusercontent.com/16974619/73449580-741a5d00-439e-11ea-8fd6-cab19e489e60.png ，你看看你那边能否访问

**Comment by damingerdai** [comment]
为什么不添加一个issues template呢？？？

**Comment by frank-zsy** [comment]
> 为什么不添加一个issues template呢？？？

对，应该用 template

**Comment by damingerdai** [comment]
pr也应该使用template吧？？？

**Comment by thinkinnight** [comment]
我们已经加上issue_template了，@damingerdai PR template还不是很了解，能介绍一下吗？谢谢！

**Comment by damingerdai** [comment]
> 我们已经加上issue_template了，@damingerdai PR template还不是很了解，能介绍一下吗？谢谢！

你创建一个pull request试试看

**Comment by thinkinnight** [comment]
知道了，多谢submit

**Comment by thinkinnight** [comment]
做了一个关于issue提交的，由于加了issue_template，已经和之前的有些区别了，是否需要换成这个issue？
https://github.com/wuhan2020/wuhan2020/issues/317

@frank-zsy

**Comment by frank-zsy** [comment]
已经有了 issue template，不再需要此 Issue
