### ISSUE TITLE
[Feature] 需要有采集其他 API 的能力

### ISSUE THREAD

**Issue by frank-zsy** [wuhan2020/data-sync#35]
需要能够定时采集其他 API 的数据，然后用落仓。

对方需要提供一个数据内容说明、API 地址、数据格式说明、一个访问凭证，我们即可开始采集他们的数据。

**Comment by c3ll256** [comment]
不太明白 是要做一个提交数据接入申请的部分吗

**Comment by frank-zsy** [comment]
> 不太明白 是要做一个提交数据接入申请的部分吗

嗯嗯，就是这个意思，很多人都自己做了 API，想并入进来，最简单的方式就是直接去 API 采集，而不需要重写一遍逻辑

**Comment by c3ll256** [comment]
> > 不太明白 是要做一个提交数据接入申请的部分吗
> 
> 嗯嗯，就是这个意思，很多人都自己做了 API，想并入进来，最简单的方式就是直接去 API 采集，而不需要重写一遍逻辑

我觉得还是需要自己出一个规范 不然都是各种各样的API规范是做不进来的。

**Comment by frank-zsy** [comment]
> 我觉得还是需要自己出一个规范 不然都是各种各样的API规范是做不进来的。

因为各种数据类型并不相同，所以只要对方提供数据结构，我觉得审核后就可以去收集了，规范话就是 HTTP 或 HTTPS API，返回 JSON 就可以了
