### ISSUE TITLE
[Ci]:  建议使用husky用于本地仓库提交代码时的校验#PwC

### ISSUE THREAD

**Issue by damingerdai** [wuhan2020/data-sync#42]
husky可以利用git hooks在提交代码时做一些lint上的操作。

这样子可以减少因为代码格式导致ci不通过的问题

**Comment by frank-zsy** [comment]
husky 是什么原理？可以介绍一下吗？git hooks 是本地配置，可以做 pre commit 的 lint，但不知道怎么修改本地文件？放在 post install 的 script 中呢？

**Comment by damingerdai** [comment]
> husky 是什么原理？可以介绍一下吗？git hooks 是本地配置，可以做 pre commit 的 lint，但不知道怎么修改本地文件？放在 post install 的 script 中呢？

@frank-zsy 不用自己修改本地文件，husky帮我们封装好了。请看我的pr： #43

**Comment by frank-zsy** [comment]
fixed by #43
