### ISSUE TITLE
[Feature] 添加一个issues和pr的template

### ISSUE THREAD

**Issue by damingerdai** [wuhan2020/data-sync#55]

**Comment by rexwangcc** [comment]
Issue 的template可能需要repo权限，PR的话根据本project的需求，可部分参考https://raw.githubusercontent.com/wuhan2020/api-server/master/.github/pull_request_template.md

**Comment by damingerdai** [comment]
thanks @rexwangcc

**Comment by frank-zsy** [comment]
fixed by #56
