### ISSUE TITLE
[Feature] 添加七牛 CDN 的推送能力

### ISSUE THREAD

**Issue by frank-zsy** [wuhan2020/data-sync#59]
目前数据更新后会推送到 GitHub 数据仓库中，但前端直接使用时非常不便，速度无法保障，故目前在数据更新后同时推送到 CDN 上，以便可以使用

**Comment by tyisme614** [comment]
这个issue 正在做吗？ @frank-zsy

**Comment by frank-zsy** [comment]
> 这个issue 正在做吗？ @frank-zsy

Doing

**Comment by tyisme614** [comment]
这个项目目前还有哪些需要做的工作呢？ @frank-zsy

**Comment by frank-zsy** [comment]
> 这个项目目前还有哪些需要做的工作呢？ @frank-zsy

我开个新的 issue 哈，有一张新的表要接入一下

**Comment by tyisme614** [comment]
好的
