### ISSUE TITLE
[Feature] 接入湖北医疗人员指定休息酒店表

### ISSUE THREAD

**Issue by frank-zsy** [wuhan2020/data-sync#69]
## 描述功能要求

参考其他已有表，接入湖北料人员指定休息酒店表
表地址：https://shimo.im/sheets/Hd9C3QytrJK3RWxG
需要注意：
- 需要接入所有各市分表，具体方式可以参考 table_hospital
- 所有 type 目前都已支持，仅需在 schema 中增加对应的配置
- 需要注意联系人和联系电话被分列了，feParser 中需要合并成目前的 contacts 格式

## 额外的信息
使用 /self-assign 认领任务

**Comment by frank-zsy** [comment]
@tyisme614 可以看看这个 Issue

**Comment by tyisme614** [comment]
好的
