### ISSUE TITLE
[Feature] 需要一个全局缓存

### ISSUE THREAD

**Issue by frank-zsy** [wuhan2020/data-sync#72]
## 描述功能要求

需要全局缓存来提供缓存能力，例如 Redis 或内存缓存均可。

场景：在对地址进行经纬度转换时，需要有全局缓存来尽量保证不需要反复发起请求。

**Comment by damingerdai** [comment]
不知道lowdb能不能满足这个需求？

**Comment by tyisme614** [comment]
redis比较靠谱吧，而且可以直接调用 egg-redis

**Comment by frank-zsy** [comment]
> redis比较靠谱吧，而且可以直接调用 egg-redis

Redis 可以的

**Comment by tyisme614** [comment]
@frank-zsy 插件搞定了，可以先用插件来实现缓存。 redis的话需要给我提供相关的服务器信息，用来测试egg-redis。
