### ISSUE TITLE
Why the data is pushed to github?

### ISSUE THREAD

**Issue by zhaofeng-shu33** [wuhan2020/data-sync#93]
## 您的问题
It seems that we can use the code of this repo to fetch the data from shimo and push them to a github repository. The frontend code uses these json data. But the frontend code is not deployed to github pages. So my question is why we need to push the data to github.

**Comment by frank-zsy** [comment]
Actually the first aim of the project is a data platform, the front pages is not an essential part of the project, we want all developers can use the data to implement their own project.

And with git as underlying VCS, we can track the history of the data, that maybe helpful for other projects.

**Comment by zhaofeng-shu33** [comment]
Indeed.
