### ISSUE TITLE
Do I need logging into shimo in order to get access to the table data

### ISSUE THREAD

**Issue by zhaofeng-shu33** [wuhan2020/data-sync#94]
## 您的问题
I can browser the data directly in browser using the shimo link. So I wonder if it is necessary to login in the code.

**Comment by frank-zsy** [comment]
But you need to parse the browser data and you can use cookie to login on browser side

**Comment by zhaofeng-shu33** [comment]
I find that shimo frontend code does not use the api to load the data. So it is undocumented and may change without notice.

**Comment by zhaofeng-shu33** [comment]
It is not difficult to summarize the undocumented api using chrome dev-tools. Many popular projects in web-crawler domain do things like this. But I think such kind of method is not the best option. By the way, shimo official teams seem not to open the application of their SDK token. This is the same like [lingxi](https://www.lingxi360.com/), which you have to contact their staff personally to apply the token. This kind of difficulty set the obstacle for developers to contribute to project like this.

**Comment by frank-zsy** [comment]
Yes, actually in wuhan2020, shimo is our sponsor from the first day, it's not a totally open platform.
