### ISSUE TITLE
cannot start from refresh to sync the data

### ISSUE THREAD

**Issue by zhaofeng-shu33** [wuhan2020/data-sync#95]
## 当前问题
I have setup both the github repo and shimo SDK token. And I can successfully synchronize the hospital table. However, the synchronization of `clinicTable` failed. Maybe there is some problems with the schema of `clinicTable`.

**Comment by frank-zsy** [comment]
Is there any error message in console? Or you can not see any change in the repo?

**Comment by zhaofeng-shu33** [comment]
![image](https://user-images.githubusercontent.com/23316477/75754872-763e5580-5d68-11ea-8d7b-de742b77e5bd.png)

**Comment by frank-zsy** [comment]
This is an error from GitHub side, you may not set the current token or your IP is considered performing abuse attack.

**Comment by zhaofeng-shu33** [comment]
Maybe. The initialization has many commits to the repo. I find each file is a single comment. GitHub may bans the IP of my workstation.

**Comment by zhaofeng-shu33** [comment]
Wait for a while and restart the server can update more data to the repos.

**Comment by frank-zsy** [comment]
OK, from my experience, change the token may also solve the problem.

**Comment by zhaofeng-shu33** [comment]
Thanks.
