### ISSUE TITLE
support fetching from other shimo tables outside of wuhan2020

### ISSUE THREAD

**Issue by zhaofeng-shu33** [wuhan2020/data-sync#97]
## 描述功能要求
https://shimo.im/sheets/qZx7ltnDo0I9BSLD/8U70d, which is a table about a non-profit program.
To fetch the table data to github without changing the table itself. The code base should be slightly modified.

**Comment by zhaofeng-shu33** [comment]
Not feasible. The given client id and secret can only fetch the data created by `wuhan2020`.

**Comment by frank-zsy** [comment]
Is that true? I think the secret can access any public tables, in fact, in data-sync, the `table_oxbridge` is not in wuhan2020 org, it is from an outside volunteer team.

**Comment by zhaofeng-shu33** [comment]
![image](https://user-images.githubusercontent.com/23316477/75774809-b19e4b80-5d8b-11ea-98ae-c4414de6f871.png)

**Comment by zhaofeng-shu33** [comment]
Schema:
```JavaScript
import { TableConfig, getCellByName } from './table';

const LawyerTable: TableConfig = {
  guid: 'qZx7ltnDo0I9BSLD',
  indexKey: 'lawyer',
  sheets: [ '律所服务人数排序表' ],
  skipRows: 1,
  skipColumns: 0,
  nameRow: 1,
  typeRow: -1,
  defaultValueRow: -1,
  maxColumn: 'O',
  getFilePath: () => 'lawyer/data.json',
  feParser: async (data: any[]) => {
    return data.map((row, id) => {
      return {
        id,
        name: getCellByName(row, '所在单位').value,
        number: getCellByName(row, '单位服务人数').value,
      };
    });
  },
    validation: () => true,
};

export default LawyerTable;
```

**Comment by zhaofeng-shu33** [comment]
> table_oxbridge

is not used in the project. Its schema is nearly empty.

**Comment by frank-zsy** [comment]
> > table_oxbridge
> 
> is not used in the project. Its schema is nearly empty.

It is used, the schema is quite simple because it is a pre table config of hospital which means it will override any records duplicated in hospital schema

You can see 
```
preTable: oxbridgeHospitalTable,
preTableDetect: row => getCellByName(row, '医院名称'),
```
in hospital schema, this means before get hospital tables, it will fetch `preTable` first and use column `医院名称` to detect as duplicate record, then replace all duplicated records in hospital with the records in pre table

**Comment by frank-zsy** [comment]
I think you may set the `maxColumn` too large, try set it to `B`

**Comment by frank-zsy** [comment]
Oh, I know, in the log, you can see `律所服务人数排序表!A-1:O-1`, if you want to support negative type and default value row in schema, you need to disable row fetch if the value is negative.

**Comment by zhaofeng-shu33** [comment]
Yes, negative -1 not works. And oxbridge is a preTable. I missed it before.

**Comment by frank-zsy** [comment]
I did not implement to support -1 type or default row before, you can add it to `shimo` service

**Comment by frank-zsy** [comment]
But I do support empty default value row, between line 121-128 in `shimo` service, you can add empty type row support just like that, and push `string` as default type in `types`, then all will be fine.

**Comment by zhaofeng-shu33** [comment]
Yes empty type row is in PR #96

**Comment by frank-zsy** [comment]
Then you need to check why the service still made the request.

BTW, the PR CI fails.

**Comment by zhaofeng-shu33** [comment]
Mostly lint problems.
I have fetched the data successfully.

**Comment by frank-zsy** [comment]
Great, welcome to be a contributor of data-sync~
